### PR TITLE
fix: Values for section 6.2 should be numbers

### LINKED ISSUE #98: `minimum=0` isn't represented property in the schema
When using default int value (0) for `minimum`, `maximum`, etc., the values are just skipped in the resulting schema.
It can be worked around with `exclusiveMinimum=-1`, but the better way would be to make `Schema.Minimum` field (as well as other related ones) a pointer.

https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.2.2
https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.2.4

### LINKED ISSUE #99: bug: `exclusiveMinimum` & `exclusiveMaximum` are represented as booleans
https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.2.5
https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.2.3

### PR DESCRIPTION
**Pull request by candiduslynx**
Closes #98
Closes #99

https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.2

### CODE REVIEW

**Comment by candiduslynx** [comment]
@samlown it's ready for review

File: reflect.go [hunk 1]
```diff
@@ -54,13 +54,13 @@ type Schema struct {
...
-	Enum              []interface{}       `json:"enum,omitempty"`              // section 6.1.2
-	Const             interface{}         `json:"const,omitempty"`             // section 6.1.3
-	MultipleOf        int                 `json:"multipleOf,omitempty"`        // section 6.2.1
-	Maximum           int                 `json:"maximum,omitempty"`           // section 6.2.2
-	ExclusiveMaximum  bool                `json:"exclusiveMaximum,omitempty"`  // section 6.2.3
-	Minimum           int                 `json:"minimum,omitempty"`           // section 6.2.4
-	ExclusiveMinimum  bool                `json:"exclusiveMinimum,omitempty"`  // section 6.2.5
+	Enum              []any               `json:"enum,omitempty"`              // section 6.1.2
+	Const             any                 `json:"const,omitempty"`             // section 6.1.3
+	MultipleOf        *json.Number        `json:"multipleOf,omitempty"`        // section 6.2.1
```
Comment (samlown) [inline reflect.go:59]: Do these need to be pointers? `json.Number` is a type of `string`, so the omitempty flag should remove them. They'll be slightly easier to use if so. Also, I think this same pattern could be applied to the `MaxLength` and `MinLength` properties (perhaps more) for the sake of consistency.

File: .golangci.yml [hunk 2]
```diff
@@ -43,6 +43,12 @@ linters-settings:
   gocritic:
     disabled-checks:
       - ifElseChain
+  gofmt:
+    rewrite-rules:
+    - pattern:     'interface{}'
+      replacement: 'any'
```
Comment (samlown) [inline .golangci.yml:49]: I wasn't convinced about this, but I wasn't up to date about the fact that Golang itself already made the transition internally, so 👍

File: reflect.go [hunk 3]
```diff
@@ -1020,6 +1017,19 @@ func ignoredByJSONSchemaTags(tags []string) bool {
 	return tags[0] == "-"
 }
 
+// toJSONNumber converts string to *json.Number
+// it'll return nil if the number is invalid
+func toJSONNumber(s string) *json.Number {
```
Comment (samlown) [inline reflect.go:1022]: Is this necessary if pointers are removed? What is the intention here? It would make sense to have a test case for whatever is trying to be caught.

**Review by samlown — COMMENTED** [review]
Thanks for this! Looks great from the outset. I've added a few questions regarding the use of pointers... I'm not convinced they're necessary, and if they are, there should be some tests to show it.

File: reflect.go (hunk 3 above)
Comment (candiduslynx) [reply reflect.go]: Moved from pointers in 372fbaa

File: reflect.go (hunk 1 above)
Comment (candiduslynx) [reply reflect.go]: Moved away from pointers in 372fbaa

Comment (candiduslynx) [reply reflect.go]: For the `minLength` & `maxLength` we have different restrictions, see https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.3.1 & https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.3.2 (they are non-negative integers)

File: reflect.go [hunk 4]
```diff
@@ -1020,6 +1016,19 @@ func ignoredByJSONSchemaTags(tags []string) bool {
 	return tags[0] == "-"
 }
 
+// toJSONNumber converts string to *json.Number.
+// It'll aso return whether the number is valid.
+func toJSONNumber(s string) (json.Number, bool) {
```
Comment (samlown) [inline reflect.go:1021]: Not sure the `bool` is necessary given that you can test for an empty number, but we can go with that.

**Review by samlown — APPROVED** [review]
LGTM! Thanks!

**Comment by candiduslynx** [comment]
@samlown could you merge & release 0.9.1?

**Comment by samlown** [comment]
New release pushed. Thanks.
